import { createApp } from "vue";
import "ant-design-vue/dist/reset.css";
import App from "./App.vue";
import router from "./router";
import piniaPersist from "pinia-plugin-persist";
import "@/assets/css/index.less";
import { createPinia } from "pinia";
const pinia = createPinia();
pinia.use(piniaPersist);
const app = createApp(App);
app.use(router);
app.use(pinia);
app.mount("#app");
